import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read = (path: string) => readFileSync(path, "utf8");
const publicPage = read("app/(marketing)/resonance/enter/page.tsx");
const entryPage = read("app/(member)/entry/page.tsx");
const visitsPage = read("app/(member)/resonance/visits/page.tsx");
const actions = read("app/(member)/resonance/visits/actions.ts");
const completePage = read("app/(member)/resonance/complete/page.tsx");
const offerPicker = read("app/(member)/resonance/complete/additional-offer-picker.tsx");
const roomEntry = read("src/lib/resonance/room-entry.ts");
const middleware = read("middleware.ts");

assert.match(middleware, /pathname === "\/"[\s\S]{0,180}rewriteResonancePath\(req, "\/resonance\/enter"\)/);
assert.doesNotMatch(middleware, /host === RESONANCE_HOST && pathname === "\/"[\s\S]{0,120}auth\.protect/);
assert.match(middleware, /"\/resonance\/enter\(\.\*\)"/);
assert.doesNotMatch(middleware, /"\/resonance\/visits\(\.\*\)"/);

assert.match(publicPage, /<details/);
assert.match(publicPage, /Choose \{roomName\}/);
assert.match(publicPage, /room\.chooseWhen/);
assert.match(publicPage, /\/entry\?room=\$\{room\.weekNumber\}/);
assert.doesNotMatch(publicPage, /line-clamp-2/);
assert.match(roomEntry, /The Hearth/);
assert.match(roomEntry, /The Becoming/);
assert.match(entryPage, /resonance\/visits\?room=/);
assert.match(visitsPage, /getResonanceRoomTarget/);
assert.match(visitsPage, /name="room"/);
assert.match(visitsPage, /data-whop-checkout-return-url=[\s\S]*roomSuffix/);
assert.match(actions, /formRoomTarget/);
assert.match(actions, /roomTarget\?\.entryPath/);
assert.match(completePage, /roomWeekNumber=\{roomTarget\?\.weekNumber\}/);
assert.match(completePage, /Continue to \$\{roomTarget\.name\}/);
assert.match(offerPicker, /name="room"/);
console.log("Resonance public sales root and account-first checkout funnel checks passed.");
