import type { ProviderSeed } from "../types";

export const zaManufacturingProviders: ProviderSeed[] = [
  {
    name: "Southern Right Foods",
    slug: "southern-right-foods",
    legalName: "Southern Right Foods (PTY) Ltd",
    website: "https://srfoods.co.za/",
    phone: "+27 21 903 5755",
    description:
      "Food manufacturer and contract packer specialising in herbs, spices, salts, powdered soups, seasoning mixes, private label, custom blending and packing.",
    administrativeArea: "Western Cape",
    locality: "Cape Town",
    servesNationally: true,
    exports: true,
    types: ["MANUFACTURER", "CO_PACKER", "PRODUCT_DEVELOPER"],
    locations: [
      {
        key: "cape-town-factory",
        label: "Cape Town factory",
        locationType: "FACTORY",
        addressLine1: "27 Muscat Road",
        addressLine2: "Saxenburg Park 1, Rustdal",
        administrativeArea: "Western Cape",
        locality: "Cape Town",
        isPrimary: true,
      },
    ],
    sources: [
      {
        key: "home",
        name: "Southern Right Foods website",
        url: "https://srfoods.co.za/",
      },
    ],
    offerings: [
      {
        name: "Private label and custom blending",
        slug: "private-label-custom-blending",
        description:
          "Private-label product development, custom blending, manufacturing and packing for herbs, spices, salts, seasonings and related speciality foods.",
        productionModel: "PRIVATE_LABEL",
        leadTimeMinDays: 14,
        leadTimeMaxDays: 28,
        leadTimeBasis: "CALENDAR_DAYS",
        categories: ["FOOD"],
        services: ["PRODUCT_DEVELOPMENT", "MANUFACTURING", "PACKAGING"],
        capabilities: ["BLENDING", "POUCH_PACKING", "SACHET_FILLING"],
        packagingFormats: ["BOTTLE", "POUCH", "SACHET", "OTHER"],
      },
      {
        name: "Contract packing",
        slug: "contract-packing",
        description:
          "Contract packing for dry food products across bottles, flexible packs, resealable pouches and sachets.",
        productionModel: "CO_PACKING",
        categories: ["FOOD"],
        services: ["PACKAGING"],
        capabilities: ["POUCH_PACKING", "SACHET_FILLING"],
        packagingFormats: ["BOTTLE", "POUCH", "SACHET", "OTHER"],
      },
    ],
    claims: [
      {
        field: "commercial.order_execution",
        claimType: "COMMERCIAL",
        value: { minWeeks: 2, maxWeeks: 4 },
        displayValue: "Orders can be executed within 2 to 4 weeks depending on size.",
        sourceKey: "home",
        evidenceSummary:
          "The provider states that order execution can take 2 to 4 weeks depending on order size.",
        staleAfterDays: 90,
      },
    ],
  },
  {
    name: "Power Blends",
    slug: "power-blends",
    legalName: "Power Blends Pty Ltd",
    website: "https://www.power-blends.com/",
    email: "sales@power-blends.com",
    phone: "+27 11 440 6165",
    description:
      "Producer and co-packer of powdered dry products for the food and beverage industry, with R&D, sourcing, blending, crushing, packing and warehousing.",
    administrativeArea: "Gauteng",
    locality: "Johannesburg",
    types: ["MANUFACTURER", "CO_PACKER", "PRODUCT_DEVELOPER"],
    locations: [
      {
        key: "linbro-business-park",
        label: "Head office and facility",
        locationType: "FACILITY",
        addressLine1: "106 Saturn Crescent",
        addressLine2: "Linbro Business Park",
        administrativeArea: "Gauteng",
        locality: "Johannesburg",
        postalCode: "2090",
        isPrimary: true,
      },
    ],
    sources: [
      {
        key: "home",
        name: "Power Blends website",
        url: "https://www.power-blends.com/",
      },
      {
        key: "contact",
        name: "Power Blends contact page",
        url: "https://www.power-blends.com/talk-to-us",
      },
    ],
    offerings: [
      {
        name: "Custom dry blending",
        slug: "custom-dry-blending",
        description:
          "Custom dry-product blending with R&D and raw-material sourcing support for food and beverage applications.",
        productionModel: "CUSTOM_MANUFACTURING",
        moqValue: 100,
        moqUnit: "KG",
        categories: ["FOOD", "BEVERAGE"],
        services: [
          "PRODUCT_DEVELOPMENT",
          "RAW_MATERIAL_SOURCING",
          "MANUFACTURING",
          "PACKAGING",
          "WAREHOUSING",
          "LOGISTICS",
        ],
        capabilities: ["BLENDING", "POWDER_BLENDING", "CRUSHING"],
        packagingFormats: ["POUCH", "SACHET", "TIN", "OTHER"],
      },
      {
        name: "Dry-product co-packing",
        slug: "dry-product-co-packing",
        description:
          "Packing of powdered beverages, vending powders, instant porridges, baking mixes, spices, soup powders and related dry products.",
        productionModel: "CO_PACKING",
        categories: ["FOOD", "BEVERAGE"],
        services: ["PACKAGING", "WAREHOUSING", "LOGISTICS"],
        capabilities: ["POUCH_PACKING", "SACHET_FILLING"],
        packagingFormats: ["POUCH", "SACHET", "TIN", "OTHER"],
      },
    ],
    claims: [
      {
        field: "commercial.moq.custom_dry_blending",
        claimType: "COMMERCIAL",
        value: 100,
        displayValue: "Custom dry blending starts at a 100 kg batch.",
        unit: "KG",
        offeringSlug: "custom-dry-blending",
        sourceKey: "home",
        evidenceSummary:
          "The provider states that customised dry blends start from a minimum batch of 100 kg.",
        staleAfterDays: 90,
      },
    ],
  },
  {
    name: "Quintessence Collections",
    slug: "quintessence-collections",
    legalName: "Quintessence Collections (Pty) Ltd",
    website: "https://quintessence.co.za/",
    email: "info@quint.co.za",
    phone: "+27 12 804 7545",
    description:
      "Cosmetic formulation and contract manufacturing facility supporting skincare, body care, spa and natural brands from development through filling and finishing.",
    administrativeArea: "Gauteng",
    locality: "Pretoria",
    types: ["MANUFACTURER", "FORMULATOR", "PRODUCT_DEVELOPER"],
    locations: [
      {
        key: "pretoria-facility",
        label: "Integrated cosmetic manufacturing facility",
        locationType: "FACTORY",
        addressLine1: "426 Skilder Street",
        addressLine2: "Silvertondale",
        administrativeArea: "Gauteng",
        locality: "Pretoria",
        isPrimary: true,
      },
    ],
    sources: [
      {
        key: "home",
        name: "Quintessence Collections website",
        url: "https://quintessence.co.za/",
      },
      {
        key: "process",
        name: "Quintessence manufacturing process",
        url: "https://quintessence.co.za/our-process/",
      },
      {
        key: "contact",
        name: "Quintessence contact page",
        url: "https://quintessence.co.za/contact/",
      },
    ],
    offerings: [
      {
        name: "Custom cosmetic development and manufacturing",
        slug: "custom-cosmetic-development",
        description:
          "Formulation, product development, contract manufacturing, filling, finishing and regulatory support for skincare and personal-care brands.",
        productionModel: "CUSTOM_FORMULATION",
        categories: ["SKINCARE", "PERSONAL_CARE"],
        services: [
          "PRODUCT_DEVELOPMENT",
          "FORMULATION",
          "REGULATORY_SUPPORT",
          "MANUFACTURING",
          "PACKAGING",
        ],
        capabilities: ["STABILITY_TESTING", "FILLING", "BATCH_CODING"],
      },
    ],
    claims: [
      {
        field: "capacity.contract_manufacturing_range",
        claimType: "CAPACITY",
        value: { publishedUpperReference: 20000, openEnded: true },
        displayValue: "Contract manufacturing is described as scaling from niche runs to 20,000+ units.",
        offeringSlug: "custom-cosmetic-development",
        sourceKey: "home",
        evidenceSummary:
          "The provider describes flexible contract manufacturing from niche runs to more than 20,000 units.",
        staleAfterDays: 180,
      },
    ],
  },
  {
    name: "Cosmetic Laboratories of South Africa",
    slug: "coslab",
    website: "https://www.coslab.co.za/",
    email: "info@coslab.co.za",
    description:
      "Cape Town contract manufacturer specialising in private-label cosmetics and toiletries from development through finished retail-ready products.",
    administrativeArea: "Western Cape",
    locality: "Cape Town",
    servesNationally: true,
    exports: true,
    types: ["MANUFACTURER", "FORMULATOR", "PRODUCT_DEVELOPER"],
    locations: [
      {
        key: "diep-river-facility",
        label: "Cape Town facility",
        locationType: "FACTORY",
        addressLine1: "Unit F9, Prime Park, Mocke Road",
        administrativeArea: "Western Cape",
        locality: "Diep River, Cape Town",
        postalCode: "7800",
        isPrimary: true,
      },
    ],
    sources: [
      {
        key: "about",
        name: "COSLAB about page",
        url: "https://www.coslab.co.za/about",
      },
      {
        key: "work-with-us",
        name: "COSLAB project intake page",
        url: "https://www.coslab.co.za/work-with-us",
      },
      {
        key: "services",
        name: "COSLAB services page",
        url: "https://www.coslab.co.za/our-services",
      },
    ],
    offerings: [
      {
        name: "Private-label cosmetics",
        slug: "private-label-cosmetics",
        description:
          "End-to-end private-label cosmetic development and manufacturing for established retailers and emerging brands.",
        productionModel: "PRIVATE_LABEL",
        moqValue: 5000,
        moqUnit: "UNITS",
        categories: ["SKINCARE", "PERSONAL_CARE"],
        services: ["PRODUCT_DEVELOPMENT", "FORMULATION", "MANUFACTURING", "PACKAGING"],
        packagingFormats: ["BOTTLE", "JAR", "DROPPER"],
      },
    ],
    claims: [
      {
        field: "commercial.moq.private_label_cosmetics",
        claimType: "COMMERCIAL",
        value: 5000,
        displayValue: "Minimum order quantities typically start from 5,000 units per SKU.",
        unit: "UNITS",
        offeringSlug: "private-label-cosmetics",
        sourceKey: "work-with-us",
        evidenceSummary:
          "COSLAB's project intake states that minimum order quantities typically start from 5,000 units per SKU.",
        staleAfterDays: 90,
      },
    ],
  },
  {
    name: "SA-Labs",
    slug: "sa-labs",
    legalName: "SA Vitamins (Pty) Ltd",
    website: "https://sa-labs.com/",
    email: "Info@Sa-Labs.com",
    phone: "+27 12 346 3333",
    description:
      "Private-label health, wellness and supplement manufacturer supporting capsules, powders, tablets, oils, packaging and brand presentation.",
    administrativeArea: "Gauteng",
    locality: "Pretoria",
    types: ["MANUFACTURER", "FORMULATOR", "PRODUCT_DEVELOPER"],
    locations: [
      {
        key: "samcor-park-lab",
        label: "Pretoria facility",
        locationType: "FACTORY",
        addressLine1: "251 Vonkprop Road",
        addressLine2: "Samcor Park",
        administrativeArea: "Gauteng",
        locality: "Pretoria",
        postalCode: "0184",
        isPrimary: true,
      },
    ],
    sources: [
      {
        key: "about",
        name: "SA-Labs about page",
        url: "https://sa-labs.com/about/",
      },
      {
        key: "services",
        name: "SA-Labs services page",
        url: "https://sa-labs.com/services/",
      },
      {
        key: "legacy-home",
        name: "SA-Labs product and FAQ page",
        url: "https://www.sa-labs.com/",
      },
    ],
    offerings: [
      {
        name: "Private-label supplements",
        slug: "private-label-supplements",
        description:
          "Private-label supplement manufacturing with formulation, production, filling, packaging and label support.",
        productionModel: "PRIVATE_LABEL",
        moqValue: 200,
        moqUnit: "UNITS",
        leadTimeMinDays: 21,
        leadTimeMaxDays: 25,
        leadTimeBasis: "WORKING_DAYS",
        categories: ["SUPPLEMENTS"],
        services: [
          "PRODUCT_DEVELOPMENT",
          "FORMULATION",
          "MANUFACTURING",
          "PACKAGING",
          "LABELLING",
        ],
        capabilities: ["ENCAPSULATION", "TABLETING", "POWDER_BLENDING", "FILLING"],
        packagingFormats: ["BOTTLE", "JAR", "POUCH", "DROPPER"],
        packagingSupplied: true,
      },
      {
        name: "White-label supplements",
        slug: "white-label-supplements",
        description: "White-label supplement option for smaller initial quantities.",
        productionModel: "WHITE_LABEL",
        moqValue: 50,
        moqUnit: "UNITS",
        categories: ["SUPPLEMENTS"],
        services: ["MANUFACTURING", "PACKAGING", "LABELLING"],
        packagingFormats: ["BOTTLE", "JAR", "POUCH"],
        packagingSupplied: true,
      },
    ],
    claims: [
      {
        field: "commercial.moq.private_label_supplements",
        claimType: "COMMERCIAL",
        value: 200,
        displayValue: "Private-label minimum order quantity: 200 units.",
        unit: "UNITS",
        offeringSlug: "private-label-supplements",
        sourceKey: "legacy-home",
        evidenceSummary: "SA-Labs publishes a minimum manufacturing order quantity of 200 units.",
        staleAfterDays: 90,
      },
      {
        field: "commercial.lead_time.private_label_supplements",
        claimType: "COMMERCIAL",
        value: { min: 21, max: 25, basis: "WORKING_DAYS" },
        displayValue: "Manufacturing lead time: 21–25 working days.",
        offeringSlug: "private-label-supplements",
        sourceKey: "legacy-home",
        evidenceSummary: "SA-Labs publishes a manufacturing lead time of 21 to 25 working days.",
        staleAfterDays: 90,
      },
      {
        field: "commercial.moq.white_label_supplements",
        claimType: "COMMERCIAL",
        value: 50,
        displayValue: "White-label option: 50-unit minimum.",
        unit: "UNITS",
        offeringSlug: "white-label-supplements",
        sourceKey: "legacy-home",
        evidenceSummary: "SA-Labs publishes a 50-unit minimum for its white-label option.",
        staleAfterDays: 90,
      },
    ],
  },
];
